### ISSUE TITLE
Reporte de Practica 8 Equipo Mana

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipomana#1]
[Reporte de P8 Equipo Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipomana/files/13273807/Reporte.de.P8.Equipo.Mana.pdf)

**Comment by Luz1727** [comment]
30 / 30

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
